"""Build a viewable data directory of whatever each source has available now.

Runs the full ingestion (parallel, per-host-gated — `pipeline.fetch('all')`),
buckets events by source, and writes a browsable directory:

    data-directory/
      INDEX.md          catalog table + live counts + links to each source file
      <source>.json     recent sample events (title, link, date, entities, themes)

The per-source JSON files ARE the different sources of data. Output is
regenerable and git-ignored — these are samples one query away from the source,
not a store (consistent with the keep-the-link storage model). Durable metadata
lives in `source_catalog.py` / `docs/source-catalog.md`.

Run: ``uv run python -m high_signal_ingest.data_directory [--days 7] [--limit 40]``
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

from . import pipeline
from .dedupe import dedupe
from .extract.entities import gazetteer_match
from .grouping import classify_themes
from .source_catalog import CATALOG, by_id
from .types import Event
from .utils import event_text, source_family

# Repo-root/data-directory (this file is .../python/ingest/src/high_signal_ingest/).
_DEFAULT_OUT = Path(__file__).resolve().parents[4] / "data-directory"


def _sample(ev: Event) -> dict[str, object]:
    text = event_text(ev)
    return {
        "title": ev.title,
        "link": ev.source_url,
        "published_at": ev.published_at.isoformat() if ev.published_at else None,
        "source": ev.source,
        "entities": gazetteer_match(text),
        "themes": classify_themes(text),
    }


def build(days: int, limit: int, out_dir: Path) -> dict[str, int]:
    out_dir.mkdir(parents=True, exist_ok=True)
    # One parallel, per-host-gated pass over every source.
    events = pipeline.fetch("all", days)  # type: ignore[arg-type]

    by_source: dict[str, list[Event]] = defaultdict(list)
    for ev in events:
        by_source[source_family(ev.source)].append(ev)

    # Cross-source dedupe over the whole corpus (corroboration preserved).
    stories = dedupe(events)
    dedupe_stats = {
        "raw": len(events),
        "unique": len(stories),
        "duplicates_collapsed": len(events) - len(stories),
        "corroborated": sum(1 for s in stories if s.distinct_sources >= 2),
    }

    counts: dict[str, int] = {}
    for entry in CATALOG:
        _floor = datetime.min.replace(tzinfo=timezone.utc)
        evs = sorted(
            by_source.get(entry.id, []),
            key=lambda e: e.published_at or _floor,  # newest first, None-safe
            reverse=True,
        )
        counts[entry.id] = len(evs)
        payload = {
            "source": entry.id,
            "provider": entry.provider,
            "access": entry.access,
            "window_days": entry.window_days,
            "role": entry.role,
            "count": len(evs),
            "samples": [_sample(e) for e in evs[:limit]],
        }
        (out_dir / f"{entry.id}.json").write_text(json.dumps(payload, indent=2, default=str))

    _write_index(out_dir, counts, days, dedupe_stats)
    return counts


def _write_index(out_dir: Path, counts: dict[str, int], days: int, dedupe_stats: dict[str, int]) -> None:
    cat = by_id()
    total = sum(counts.values())
    live = sum(1 for v in counts.values() if v > 0)
    lines = [
        "# Data directory",
        "",
        f"> Generated by `data_directory.py` over a **{days}-day** window. "
        f"**{total} sample events** across **{live}/{len(cat)} sources** with data right now.",
        "> Regenerate: `uv run python -m high_signal_ingest.data_directory`. "
        "Each row links to that source's JSON of recent samples.",
        "",
        f"**De-duplication:** {dedupe_stats['raw']} raw events → "
        f"**{dedupe_stats['unique']} unique stories** "
        f"({dedupe_stats['duplicates_collapsed']} duplicates collapsed; "
        f"{dedupe_stats['corroborated']} corroborated by ≥2 sources). "
        "Deterministic — shared canonical URL + title token-overlap, no embeddings.",
        "",
        "Empty sources are usually key-gated (`free-key`/`optional-key`) or simply had "
        "nothing new in the window — see Access. Storage model + full metadata: "
        "[`docs/source-catalog.md`](../docs/source-catalog.md).",
        "",
        "| Source | Available now | History | Access | Role | Data |",
        "|---|--:|--:|---|---|---|",
    ]
    for entry in sorted(CATALOG, key=lambda e: (-counts.get(e.id, 0), e.id)):
        n = counts.get(entry.id, 0)
        avail = str(n) if n else ("— (needs key)" if "key" in entry.access and "keyless" not in entry.access else "—")
        lines.append(
            f"| `{entry.id}` | {avail} | {entry.window_days}d | {entry.access} "
            f"| {entry.role} | [{entry.id}.json](./{entry.id}.json) |"
        )
    lines.append("")
    (out_dir / "INDEX.md").write_text("\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a viewable data directory of available source data.")
    parser.add_argument("--days", type=int, default=7)
    parser.add_argument("--limit", type=int, default=40, help="max sample events per source file")
    parser.add_argument("--out", default=str(_DEFAULT_OUT))
    args = parser.parse_args([a for a in __import__("sys").argv[1:] if a != "--"])

    out_dir = Path(args.out)
    counts = build(args.days, args.limit, out_dir)
    live = {k: v for k, v in sorted(counts.items(), key=lambda kv: kv[1], reverse=True) if v}
    print(f"wrote {out_dir}/  ({sum(counts.values())} samples, {len(live)} live sources)")
    for k, v in live.items():
        print(f"  {k:16} {v}")


if __name__ == "__main__":
    main()
