import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
import './globals.css';
import { AnalyticsProvider } from '@/components/posthog-provider';
import { SaaSMakerFeedback } from '@/components/saasmaker-feedback';
import { VitalsReporter } from '@/components/VitalsReporter';
import { AuthNav } from '@/components/auth/AuthNav';
import { PrimaryNav } from '@/components/system/PrimaryNav';
import { SiteFooter } from '@/components/system/SiteFooter';
import { SITE_DESCRIPTION, SITE_NAME, SITE_TAGLINE, SITE_TWITTER, SITE_URL } from '@/lib/site';

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${SITE_NAME} — ${SITE_TAGLINE}`,
    template: `%s — ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  authors: [{ name: SITE_NAME, url: SITE_URL }],
  keywords: [
    'daily brief',
    'stocks',
    'startups',
    'finance',
    'technology',
    'ai signals',
    'hit-rate',
    'evidence-first',
    'market intelligence',
    'agent evaluation',
  ],
  // Do NOT set a site-wide canonical here — Next inherits it onto every
  // page and de-indexes the corpus. Homepage / deep pages set self-canonicals.
  alternates: {
    types: {
      'application/rss+xml': [
        { url: `${SITE_URL}/signals/rss`, title: 'High Signal — published signals' },
        { url: `${SITE_URL}/digest/rss`, title: 'High Signal — weekly digest' },
      ],
      'application/atom+xml': [
        { url: `${SITE_URL}/signals/atom`, title: 'High Signal — published signals (atom)' },
        { url: `${SITE_URL}/digest/atom`, title: 'High Signal — weekly digest (atom)' },
      ],
    },
  },
  openGraph: {
    type: 'website',
    url: SITE_URL,
    siteName: SITE_NAME,
    title: `${SITE_NAME} — ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
    locale: 'en_US',
    images: [
      {
        url: '/opengraph-image',
        width: 1200,
        height: 630,
        alt: `${SITE_NAME} — Daily Brief`,
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: `${SITE_NAME} — ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
    creator: SITE_TWITTER,
    images: ['/opengraph-image'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const clerkConfigured = Boolean(
    process.env['NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY'] && process.env['CLERK_SECRET_KEY']
  );
  const app = (
    <AnalyticsProvider>
      <PrimaryNav />
      <div aria-hidden="true" className="h-14" />
      {clerkConfigured ? <AuthNav /> : null}
      {children}
      <SiteFooter />
      <SaaSMakerFeedback />
      <VitalsReporter />
    </AnalyticsProvider>
  );

  return (
    <html lang="en">
      <head>
        {/* fleet-jsonld:start (generated by apply-agent-surfaces; edit registry, not this) */}
        <script
          type="application/ld+json"
          // biome-ignore lint/security/noDangerouslySetInnerHtml: fleet-generated JSON-LD
          dangerouslySetInnerHTML={{
            __html: `{"@context":"https://schema.org","@graph":[{"@type":"Organization","@id":"https://sassmaker.com/#org","name":"SaaS Maker (Foundry)","url":"https://sassmaker.com","sameAs":["https://sassmaker.com","https://github.com/High-Signal-App/high-signal"]},{"@type":"SoftwareApplication","@id":"https://highsignal.app/#app","name":"High Signal","url":"https://highsignal.app","description":"Daily synthesized brief on technology, startups, and finance — five sections with inline hit-rates, no signup required.","publisher":{"@id":"https://sassmaker.com/#org"}}]}`,
          }}
        />
        {/* fleet-jsonld:end */}
      </head>
      <body className="min-h-dvh font-sans antialiased">
        {clerkConfigured ? <ClerkProvider>{app}</ClerkProvider> : app}
      </body>
    </html>
  );
}
