import type { Metadata } from 'next';
import Script from 'next/script';
import './globals.css';
import { AnalyticsProvider } from '@/components/posthog-provider';
import { VitalsReporter } from '@/components/VitalsReporter';
import { PrimaryNav } from '@/components/system/PrimaryNav';
import { SiteFooter } from '@/components/system/SiteFooter';
import {
  clampDescription,
  SITE_DESCRIPTION,
  SITE_NAME,
  SITE_TAGLINE,
  SITE_TWITTER,
  SITE_URL,
} from '@/lib/site';

export const metadata: Metadata = {
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/icon.svg', type: 'image/svg+xml' },
      { url: '/favicon.ico', sizes: 'any' },
    ],
    apple: '/apple-touch-icon.png',
  },

  metadataBase: new URL(SITE_URL),
  title: {
    default: `${SITE_NAME} — ${SITE_TAGLINE}`,
    template: `%s — ${SITE_NAME}`,
  },
  description: clampDescription(SITE_DESCRIPTION),
  applicationName: SITE_NAME,
  authors: [{ name: SITE_NAME, url: SITE_URL }],
  keywords: [
    'daily brief',
    'stocks',
    'startups',
    'finance',
    'technology',
    'ai signals',
    'hit-rate',
    'evidence-first',
    'market intelligence',
    'source provenance',
  ],
  // Do NOT set a site-wide canonical here — Next inherits it onto every
  // page and de-indexes the corpus. Homepage / deep pages set self-canonicals.
  alternates: {
    types: {
      'application/rss+xml': [
        { url: `${SITE_URL}/signals/rss`, title: 'High Signal — published signals' },
      ],
      'application/atom+xml': [
        { url: `${SITE_URL}/signals/atom`, title: 'High Signal — published signals (atom)' },
      ],
    },
  },
  openGraph: {
    type: 'website',
    url: SITE_URL,
    siteName: SITE_NAME,
    title: `${SITE_NAME} — ${SITE_TAGLINE}`,
    description: clampDescription(SITE_DESCRIPTION),
    locale: 'en_US',
    images: [
      {
        url: '/opengraph-image',
        width: 1200,
        height: 630,
        alt: `${SITE_NAME} — Daily Brief`,
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: `${SITE_NAME} — ${SITE_TAGLINE}`,
    description: clampDescription(SITE_DESCRIPTION),
    creator: SITE_TWITTER,
    images: ['/opengraph-image'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // No reader auth provider: High Signal is fully public. Cloudflare Access
  // protects only the bounded operator paths.
  const app = (
    <AnalyticsProvider>
      <PrimaryNav />
      <div aria-hidden="true" className="h-14" />
      {children}
      <SiteFooter />
      <VitalsReporter />
    </AnalyticsProvider>
  );

  return (
    <html lang="en" data-reading-view="brief" suppressHydrationWarning>
      <head>
        <script
          // biome-ignore lint/security/noDangerouslySetInnerHtml: guarded local-only preference prevents a layout flash
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var v=localStorage.getItem('high-signal-reading-view');if(v==='newspaper')document.documentElement.dataset.readingView='newspaper'}catch(e){}})()`,
          }}
        />
        {/* fleet-jsonld:start (generated by apply-agent-surfaces; edit registry, not this) */}
        <script
          type="application/ld+json"
          // biome-ignore lint/security/noDangerouslySetInnerHtml: fleet-generated JSON-LD
          dangerouslySetInnerHTML={{
            __html: `{"@context":"https://schema.org","@graph":[{"@type":"Person","@id":"https://sarthakagrawal.dev/#person","name":"Sarthak Agrawal","jobTitle":"AI Infrastructure & Product Engineer","url":"https://sarthakagrawal.dev","image":"https://avatars.githubusercontent.com/u/43884471?v=4","sameAs":["https://sarthakagrawal.dev","https://www.linkedin.com/in/sarthakagrawal927","https://github.com/sarthakagrawal927","https://x.com/sarthakcodes","https://huggingface.co/sarthakagrawal927"],"knowsAbout":["AI infrastructure","Local-first software","Post-training language models","AI code review","Cloudflare Workers","TypeScript","Rust"],"affiliation":{"@type":"Organization","@id":"https://sassmaker.com/#app","name":"SaaS Maker","url":"https://sassmaker.com"}},{"@type":"WebSite","@id":"https://highsignal.app/#app","name":"High Signal","alternateName":["HighSignal","highsignal.app"],"url":"https://highsignal.app","description":"Free public Daily Brief on technology, startups, and finance, organized into three evidence-qualified sections with cited sources and a public hit-rate ledger.","publisher":{"@id":"https://sarthakagrawal.dev/#person"},"sameAs":["https://github.com/High-Signal-App/high-signal"]}]}`,
          }}
        />
        {/* fleet-jsonld:end */}
      </head>
      <body className="min-h-dvh font-sans antialiased">
        {app}
        {/* Microsoft Clarity — session replay + heatmaps (additive; PostHog stays) */}
        <Script id="microsoft-clarity" strategy="lazyOnload">
          {`(function(c,l,a,r,i,t,y){c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/y39u4kk9oq";y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);})(window,document,"clarity","script","y39u4kk9oq");window.clarity("set","project_id","high-signal");`}
        </Script>
        <Script
          src="https://sassmaker.com/project-strip.js"
          data-project="high-signal"
          strategy="lazyOnload"
        />
        <Script
          src="https://sassmaker.com/ai-chat-footer.js"
          data-name="High Signal"
          strategy="lazyOnload"
        />
      </body>
    </html>
  );
}
