import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { BackLink, HeroHeader, PageShell, Panel, StatGrid } from '@/components/system/HighSignalUI';
import { SITE_URL } from '@/lib/site';
import { CompanyUniverseList } from '../../CompanyUniverseList';
import {
  CASE_STUDIES,
  CASE_STUDIES_TOTAL_PAGES,
  COMPANY_UNIVERSE,
  FLOW,
  getCaseStudiesPage,
} from '../../data';

interface PageProps {
  params: Promise<{ page: string }>;
}

export const dynamic = 'force-static';

export function generateStaticParams() {
  return Array.from({ length: CASE_STUDIES_TOTAL_PAGES - 1 }, (_, index) => ({
    page: String(index + 2),
  }));
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const page = Number((await params).page);
  if (!Number.isInteger(page) || page < 2 || page > CASE_STUDIES_TOTAL_PAGES) {
    return {};
  }

  return {
    title: `Company universe, page ${page} — High Signal`,
    description: `Page ${page} of the generated High Signal company universe with source-backed companies and competitor mappings.`,
    alternates: { canonical: `${SITE_URL}/case-studies/page/${page}` },
  };
}

export default async function PaginatedCaseStudiesPage({ params }: PageProps) {
  const page = Number((await params).page);
  if (!Number.isInteger(page) || page < 2 || page > CASE_STUDIES_TOTAL_PAGES) {
    notFound();
  }

  const companies = getCaseStudiesPage(page);
  const withCompetitors = CASE_STUDIES.filter((item) => item.competitors.length > 0).length;

  return (
    <PageShell max="max-w-5xl">
      <BackLink href="/case-studies">back to first page</BackLink>
      <HeroHeader eyebrow="generated artifact" title={`Company universe, page ${page}`} size="md">
        Paginated source-backed product repertoire generated by High Signal.
      </HeroHeader>

      <StatGrid
        items={[
          ...FLOW,
          {
            label: 'coverage',
            value: withCompetitors.toLocaleString(),
            sub: 'Companies with mapped competitors.',
          },
          {
            label: 'last updated',
            value: COMPANY_UNIVERSE.generatedAt.slice(0, 10),
            sub: `${COMPANY_UNIVERSE.generatedAt.slice(11, 16)} UTC`,
          },
        ]}
      />

      <Panel eyebrow="source boundary" title="100% High Signal generated">
        <p className="mt-3 max-w-4xl text-sm leading-6 text-[var(--color-muted)]">
          Generated at {COMPANY_UNIVERSE.generatedAt.slice(0, 16).replace('T', ' ')} UTC by{' '}
          <code>{COMPANY_UNIVERSE.generatedBy}</code>. This paginated route is static and crawlable,
          while the same generated run is synced into D1 for API/search reads.
        </p>
      </Panel>

      <CompanyUniverseList companies={companies} page={page} />
    </PageShell>
  );
}
