import type { Metadata } from 'next';
import { BackLink, HeroHeader, PageShell, Panel, StatGrid } from '@/components/system/HighSignalUI';
import { SITE_URL } from '@/lib/site';
import { CompanyUniverseList } from './CompanyUniverseList';
import { CompanyLookupForm } from './CompanyLookupForm';
import { CASE_STUDIES, COMPANY_UNIVERSE, FLOW, getCaseStudiesPage } from './data';

export const dynamic = 'force-static';

export const metadata: Metadata = {
  title: 'Company universe — High Signal',
  description:
    'Generated High Signal company universe with source-backed companies and competitor mappings.',
  alternates: { canonical: `${SITE_URL}/case-studies` },
};

export default function CaseStudiesPage() {
  const withCompetitors = CASE_STUDIES.filter((item) => item.competitors.length > 0).length;
  const page = 1;
  const companies = getCaseStudiesPage(page);

  return (
    <PageShell max="max-w-5xl">
      <BackLink href="/explore">back to explore</BackLink>
      <HeroHeader eyebrow="generated artifact" title="Company universe" size="md">
        Source-backed product repertoire generated by High Signal. Every row comes from the
        generated artifact and includes competitor mappings.
      </HeroHeader>

      <StatGrid
        items={[
          ...FLOW,
          {
            label: 'coverage',
            value: withCompetitors.toLocaleString(),
            sub: 'Companies with mapped competitors.',
          },
          {
            label: 'last updated',
            value: COMPANY_UNIVERSE.generatedAt.slice(0, 10),
            sub: `${COMPANY_UNIVERSE.generatedAt.slice(11, 16)} UTC`,
          },
        ]}
      />

      <Panel eyebrow="source boundary" title="100% High Signal generated">
        <p className="mt-3 max-w-4xl text-sm leading-6 text-[var(--color-muted)]">
          Generated at {COMPANY_UNIVERSE.generatedAt.slice(0, 16).replace('T', ' ')} UTC by{' '}
          <code>{COMPANY_UNIVERSE.generatedBy}</code>. Source inputs:{' '}
          {COMPANY_UNIVERSE.sourceInputs.map((source) => source.label).join(', ')}. Competitors are
          mapped by: {COMPANY_UNIVERSE.competitorMapping.method}. The same generated run is synced
          into D1 for API/search reads; this static artifact keeps the SEO pages crawlable.
        </p>
        <CompanyLookupForm />
      </Panel>

      <CompanyUniverseList companies={companies} page={page} />
    </PageShell>
  );
}
