import type { Metadata, Route } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { BackLink, HeroHeader, PageShell, Panel, StatGrid } from '@/components/system/HighSignalUI';
import { fetchJson } from '@/lib/api';
import { SITE_URL } from '@/lib/site';
import { getSimilarCompanyCluster } from '../company-search';
import {
  CASE_STUDIES,
  COMPANY_UNIVERSE,
  COMPANY_UNIVERSE_LAST_UPDATED,
  type UniverseCompany,
  getCaseStudy,
} from '../data';

interface PageProps {
  params: Promise<{ slug: string }>;
}

export const dynamicParams = true;

interface LiveCompany extends UniverseCompany {
  status?: string;
  domain?: string | null;
  updatedAt?: string | null;
  requestedAt?: string | null;
  lastEnrichedAt?: string | null;
}

interface LiveCompanyResponse {
  company: LiveCompany;
  competitors: LiveCompany['competitors'];
}

async function getLiveCompany(slug: string): Promise<LiveCompany | null> {
  try {
    const payload = await fetchJson<LiveCompanyResponse>(
      `/company-universe/${encodeURIComponent(slug)}`
    );
    return { ...payload.company, competitors: payload.competitors };
  } catch {
    return null;
  }
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const study = getCaseStudy(slug) ?? (await getLiveCompany(slug));
  if (!study) {
    return {};
  }

  return {
    title: `${study.name} — High Signal company universe`,
    description:
      study.description ||
      `${study.name} source-backed company profile with High Signal competitor mappings.`,
    alternates: { canonical: `${SITE_URL}/case-studies/${study.slug}` },
  };
}

export default async function CaseStudyDetailPage({ params }: PageProps) {
  const { slug } = await params;
  const staticStudy = getCaseStudy(slug);
  const liveStudy = await getLiveCompany(slug);
  const study: LiveCompany | null = liveStudy
    ? { ...staticStudy, ...liveStudy }
    : staticStudy
      ? { ...staticStudy }
      : null;
  if (!study) {
    notFound();
  }
  const lastUpdated = study.updatedAt ?? COMPANY_UNIVERSE_LAST_UPDATED;
  const sourceMode = liveStudy ? 'D1 lookup' : 'artifact cache';
  const status = study.status ?? 'generated';
  const artifactCluster = getSimilarCompanyCluster(CASE_STUDIES, study);
  const similarityCluster = artifactCluster.length
    ? artifactCluster
    : study.competitors.map((edge) => ({
        company: getCaseStudy(edge.slug) ?? {
          slug: edge.slug,
          name: edge.name ?? edge.slug,
          description: '',
          category: study.category,
          investors: [],
          sourceEvidence: [],
          competitors: [],
        },
        score: edge.score,
        reason: edge.reason,
      }));

  return (
    <PageShell max="max-w-5xl">
      <BackLink href="/case-studies">back to company universe</BackLink>
      <HeroHeader eyebrow={study.category} title={study.name} size="md">
        {study.description || 'Source-backed company entry generated by High Signal.'}
      </HeroHeader>

      <StatGrid
        items={[
          {
            label: 'sources',
            value: String(study.sourceEvidenceCount ?? study.sourceEvidence.length),
            sub: 'Evidence entries preserved.',
          },
          {
            label: 'affiliations',
            value: String(study.investors.length),
            sub: study.investors.join(', '),
          },
          {
            label: 'competitors',
            value: String(study.competitors.length),
            sub: 'Mapped from High Signal graph features.',
          },
          {
            label: 'status',
            value: status.replace(/_/g, ' '),
            sub: sourceMode,
          },
          {
            label: 'last updated',
            value: lastUpdated.slice(0, 10),
            sub: `${lastUpdated.slice(11, 16)} UTC`,
          },
        ]}
      />

      <section className="mt-12 grid gap-5 lg:grid-cols-[minmax(0,0.95fr)_minmax(0,1.05fr)]">
        <Panel eyebrow="source evidence" title="Why this company exists here">
          <div className="mt-5 space-y-4">
            {study.sourceEvidence.length === 0 && (
              <p className="text-sm leading-6 text-[var(--color-muted)]">
                Source details are temporarily unavailable; the generated evidence count is
                preserved in the artifact cache.
              </p>
            )}
            {study.sourceEvidence.map((item) => (
              <div
                key={`${item.source}-${item.position}-${item.title}`}
                className="border-t border-[var(--color-line)] pt-4"
              >
                <div className="flex flex-wrap items-baseline justify-between gap-3">
                  <h2 className="text-base font-medium text-zinc-100">{item.fund}</h2>
                  <span className="font-mono text-[10px] uppercase tracking-[0.14em] text-zinc-500">
                    {item.source} #{item.position}
                  </span>
                </div>
                {item.description && (
                  <p className="mt-2 text-sm leading-6 text-[var(--color-muted)]">
                    {item.description}
                  </p>
                )}
                <a
                  className="mt-2 inline-block font-mono text-[10px] uppercase tracking-[0.14em] text-[var(--color-accent)] hover:underline"
                  href={item.sourceUrl}
                >
                  source
                </a>
              </div>
            ))}
          </div>
        </Panel>

        <div className="space-y-5">
          <Panel eyebrow="generated read" title="High Signal interpretation">
            <p className="mt-3 text-sm leading-6 text-[var(--color-muted)]">
              {study.name} is classified as{' '}
              <strong className="text-zinc-200">{study.category}</strong> from source descriptions
              and fund-directory context. Similar companies below are ranked from offline product
              facets and meaningful description overlap; category and source affiliation can only
              strengthen an existing product match. For lookup-created rows, the profile starts as
              pending enrichment until deeper source collection runs.
            </p>
          </Panel>

          {study.entities && study.entities.length > 0 && (
            <Panel eyebrow="offline extraction" title="Product facets">
              <div className="mt-4 flex flex-wrap gap-2">
                {study.entities.map((entity) => (
                  <span
                    key={`${entity.label}-${entity.text}`}
                    title={`${entity.label} · ${Math.round(entity.score * 100)}% model score`}
                    className="border border-[var(--color-line)] px-2 py-1 font-mono text-[10px] uppercase tracking-[0.1em] text-zinc-400"
                  >
                    {entity.text}
                  </span>
                ))}
              </div>
            </Panel>
          )}

          <Panel eyebrow="mapping method" title="Similarity graph">
            <p className="mt-3 text-sm leading-6 text-[var(--color-muted)]">
              Local clusters rerank extracted product concepts and description terms. The generated
              graph remains the fallback for sparse descriptions:{' '}
              {COMPANY_UNIVERSE.competitorMapping.method}. Minimum fallback score:{' '}
              {COMPANY_UNIVERSE.competitorMapping.minimumScore}; max competitors:{' '}
              {COMPANY_UNIVERSE.competitorMapping.maxCompetitorsPerCompany}.
            </p>
          </Panel>
        </div>
      </section>

      <section className="mt-8" aria-labelledby="similar-company-cluster">
        <div className="flex flex-wrap items-end justify-between gap-3">
          <div>
            <div className="font-mono text-[10px] uppercase tracking-[0.18em] text-zinc-500">
              discovery cluster
            </div>
            <h2 id="similar-company-cluster" className="mt-2 text-xl font-medium text-zinc-100">
              Companies similar to {study.name}
            </h2>
          </div>
          <span className="font-mono text-[10px] uppercase tracking-[0.14em] text-zinc-500">
            {study.category} · {similarityCluster.length} peers
          </span>
        </div>
        <p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--color-muted)]">
          A deterministic local cluster built from offline product facets and meaningful description
          terms. Category and selected-institution affiliation provide bounded tie-breaks. Open any
          peer to continue exploring its cluster.
        </p>
        <div className="mt-4 grid gap-3 md:grid-cols-2">
          {similarityCluster.map(({ company, score, reason }) => (
            <Link
              key={company.slug}
              href={`/case-studies/${company.slug}` as Route}
              className="border border-[var(--color-line)] p-4 transition hover:border-zinc-600"
            >
              <div className="flex items-center justify-between gap-4">
                <h3 className="text-base font-medium text-zinc-100">{company.name}</h3>
                <span className="font-mono text-[10px] uppercase tracking-[0.14em] text-zinc-500">
                  match {score}
                </span>
              </div>
              <p className="mt-2 text-sm leading-6 text-zinc-400">
                {company.description || `${company.category} company.`}
              </p>
              <p className="mt-2 text-xs leading-5 text-[var(--color-muted)]">{reason}</p>
            </Link>
          ))}
        </div>
      </section>
    </PageShell>
  );
}
