/**
 * Build-time bundled India D2C opportunity artifact.
 *
 * This file is regenerated by `scripts/d2c-opportunities-bundle.ts` after the
 * weekly collector (`python/ingest/.../d2c_opportunities.py`) writes a new
 * `data/d2c-opportunities/<YYYY-MM-DD>.json`. The worker and web app import
 * this module so they can render the latest cited evidence without a runtime
 * filesystem read (both deploy to Cloudflare Workers).
 *
 * When no artifact has been generated yet, this is `null` and the renderer
 * falls back to seed-only briefs (conservative `watch` verdicts).
 *
 * DO NOT edit by hand — run `pnpm d2c:bundle` after a collector run.
 */

import type { D2COpportunityArtifact } from "./d2c-opportunities";

export const BUNDLED_D2C_ARTIFACT: D2COpportunityArtifact | null = {
  "generatedAt": "2026-07-05T21:08:06.939912+00:00",
  "region": "IN",
  "niches": [
    {
      "nicheSlug": "hair-growth-scalp-support",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-05T21:07:46.041720+00:00",
      "notes": "diversity=0.00; competition/pricing/ad/agent deferred (marketplace + Meta Ad Library + agent prompts are Slice 3/4)"
    },
    {
      "nicheSlug": "lip-intimate-skincare-sensitive",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-05T21:07:34.023528+00:00",
      "notes": "diversity=0.00; competition/pricing/ad/agent deferred (marketplace + Meta Ad Library + agent prompts are Slice 3/4)"
    },
    {
      "nicheSlug": "hard-water-hair-care",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-05T21:07:34.240377+00:00",
      "notes": "diversity=0.00; competition/pricing/ad/agent deferred (marketplace + Meta Ad Library + agent prompts are Slice 3/4)"
    },
    {
      "nicheSlug": "beard-dandruff-beard-scalp",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-05T21:07:50.454016+00:00",
      "notes": "diversity=0.00; competition/pricing/ad/agent deferred (marketplace + Meta Ad Library + agent prompts are Slice 3/4)"
    },
    {
      "nicheSlug": "post-gym-mens-skin-wipes",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-05T21:08:06.939722+00:00",
      "notes": "diversity=0.00; competition/pricing/ad/agent deferred (marketplace + Meta Ad Library + agent prompts are Slice 3/4)"
    },
    {
      "nicheSlug": "delivery-rider-phone-accessories",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-05T21:07:50.292955+00:00",
      "notes": "diversity=0.00; competition/pricing/ad/agent deferred (marketplace + Meta Ad Library + agent prompts are Slice 3/4)"
    },
    {
      "nicheSlug": "heat-resistant-phone-mounts",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-05T21:07:34.281606+00:00",
      "notes": "diversity=0.00; competition/pricing/ad/agent deferred (marketplace + Meta Ad Library + agent prompts are Slice 3/4)"
    },
    {
      "nicheSlug": "office-chai-healthy-snacks",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-05T21:07:34.031307+00:00",
      "notes": "diversity=0.00; competition/pricing/ad/agent deferred (marketplace + Meta Ad Library + agent prompts are Slice 3/4)"
    },
    {
      "nicheSlug": "diabetic-friendly-travel-snacks",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-05T21:07:45.399404+00:00",
      "notes": "diversity=0.00; competition/pricing/ad/agent deferred (marketplace + Meta Ad Library + agent prompts are Slice 3/4)"
    },
    {
      "nicheSlug": "high-protein-regional-snacks",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-05T21:07:34.061356+00:00",
      "notes": "diversity=0.00; competition/pricing/ad/agent deferred (marketplace + Meta Ad Library + agent prompts are Slice 3/4)"
    },
    {
      "nicheSlug": "affordable-home-gym-under-5000",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-05T21:07:34.002491+00:00",
      "notes": "diversity=0.00; competition/pricing/ad/agent deferred (marketplace + Meta Ad Library + agent prompts are Slice 3/4)"
    },
    {
      "nicheSlug": "womens-gym-shorts-fit",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-05T21:07:34.044260+00:00",
      "notes": "diversity=0.00; competition/pricing/ad/agent deferred (marketplace + Meta Ad Library + agent prompts are Slice 3/4)"
    },
    {
      "nicheSlug": "baby-lotions-transparent-ingredients",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-05T21:07:50.748131+00:00",
      "notes": "diversity=0.00; competition/pricing/ad/agent deferred (marketplace + Meta Ad Library + agent prompts are Slice 3/4)"
    },
    {
      "nicheSlug": "ayurvedic-face-care-proof-first",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-05T21:07:34.021477+00:00",
      "notes": "diversity=0.00; competition/pricing/ad/agent deferred (marketplace + Meta Ad Library + agent prompts are Slice 3/4)"
    },
    {
      "nicheSlug": "sustainable-cleaning-laundry-refills",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-05T21:07:34.038571+00:00",
      "notes": "diversity=0.00; competition/pricing/ad/agent deferred (marketplace + Meta Ad Library + agent prompts are Slice 3/4)"
    },
    {
      "nicheSlug": "pet-health-supplements",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-05T21:07:50.388666+00:00",
      "notes": "diversity=0.00; competition/pricing/ad/agent deferred (marketplace + Meta Ad Library + agent prompts are Slice 3/4)"
    },
    {
      "nicheSlug": "oral-care-sub-niches",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-05T21:07:34.034321+00:00",
      "notes": "diversity=0.00; competition/pricing/ad/agent deferred (marketplace + Meta Ad Library + agent prompts are Slice 3/4)"
    },
    {
      "nicheSlug": "sleep-stress-support-products",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-05T21:07:34.033013+00:00",
      "notes": "diversity=0.00; competition/pricing/ad/agent deferred (marketplace + Meta Ad Library + agent prompts are Slice 3/4)"
    },
    {
      "nicheSlug": "intimate-hygiene",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-05T21:07:45.615081+00:00",
      "notes": "diversity=0.00; competition/pricing/ad/agent deferred (marketplace + Meta Ad Library + agent prompts are Slice 3/4)"
    },
    {
      "nicheSlug": "condiments-sauces-regional-identity",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-05T21:07:50.908972+00:00",
      "notes": "diversity=0.00; competition/pricing/ad/agent deferred (marketplace + Meta Ad Library + agent prompts are Slice 3/4)"
    }
  ]
};
