/**
 * Build-time bundled India D2C opportunity artifact.
 *
 * This file is regenerated by `scripts/d2c-opportunities-bundle.ts` after the
 * weekly collector (`python/ingest/.../d2c_opportunities.py`) writes a new
 * `data/d2c-opportunities/<YYYY-MM-DD>.json`. The worker and web app import
 * this module so they can render the latest cited evidence without a runtime
 * filesystem read (both deploy to Cloudflare Workers).
 *
 * When no artifact has been generated yet, this is `null` and the renderer
 * falls back to seed-only briefs (conservative `watch` verdicts).
 *
 * DO NOT edit by hand — run `pnpm d2c:bundle` after a collector run.
 */

import type { D2COpportunityArtifact } from "./d2c-opportunities";

export const BUNDLED_D2C_ARTIFACT: D2COpportunityArtifact | null = {
  "generatedAt": "2026-07-13T10:23:12.215172+00:00",
  "region": "IN",
  "niches": [
    {
      "nicheSlug": "hair-growth-scalp-support",
      "demandScore": 0.85,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [
        {
          "sourceClass": "community",
          "url": "https://reddit.com/r/tressless/comments/1uv3g1x/is_there_anything_left_for_me/",
          "source": "reddit:tressless",
          "snippet": "Is there anything left for me? — Losing massive amount of hair despite being on 2.g minoxidil tablets twice a day. Dutasteride 0.g everyday. Also got hai transplant but still losing both native and t…",
          "observedAt": "2026-07-13T06:22:33+00:00"
        },
        {
          "sourceClass": "community",
          "url": "https://reddit.com/r/tressless/comments/1uuz29q/45_months_on_finasteride_and_minoxidil/",
          "source": "reddit:tressless",
          "snippet": "4.5 Months on Finasteride And Minoxidil — It’s my first time ever after almost 4.5 years of being bald letting my hair grow longer. I’m insanely happy with the results but my hairline is still a Norw…",
          "observedAt": "2026-07-13T02:36:05+00:00"
        },
        {
          "sourceClass": "community",
          "url": "https://reddit.com/r/tressless/comments/1uuxgz6/abril_até_agora_em_uso_de_medicação_via_oral/",
          "source": "reddit:tressless",
          "snippet": "Abril até agora, em uso de medicação via oral + transplante agendado — Transplante capilar agendado para agosto/27 Em uso de minoxidil 2.5mg + dutasterida 0.5mg Podemos dizer que há uma melhora bacan…",
          "observedAt": "2026-07-13T01:20:13+00:00"
        },
        {
          "sourceClass": "community",
          "url": "https://reddit.com/r/tressless/comments/1uuwnko/wasted_a_whole_year_on_an_expensive_natural/",
          "source": "reddit:tressless",
          "snippet": "Wasted a whole year on an expensive \"natural treatment\" just to realize I am a hyper responder. — This is more of a vent than anything but was wondering if any of you did the same thing and laugh abo…",
          "observedAt": "2026-07-13T00:42:27+00:00"
        },
        {
          "sourceClass": "community",
          "url": "https://reddit.com/r/tressless/comments/1uuvmyx/finally_some_progress_after_2_years_of_fighting/",
          "source": "reddit:tressless",
          "snippet": "Finally some progress after 2 years of fighting my aggressive hairloss — Edit: pictures: https://imgur.com/a/iPpDEjy In early 2023, my brother first noticed that he could see my scalp and my hair was…",
          "observedAt": "2026-07-12T23:57:32+00:00"
        },
        {
          "sourceClass": "community",
          "url": "https://reddit.com/r/tressless/comments/1uusx9f/breezula_is_the_final_brick_in_the_wall/",
          "source": "reddit:tressless",
          "snippet": "Breezula is the final brick in the wall — For many years, us baldingers have been lacking a topical anti-androgen solution. We have system AR inhibitors in Finasteride and Dutasteride. We have growth…",
          "observedAt": "2026-07-12T22:01:54+00:00"
        },
        {
          "sourceClass": "community",
          "url": "https://reddit.com/r/tressless/comments/1uus8l3/6_months_with_fin_1mg_and_min_foam/",
          "source": "reddit:tressless",
          "snippet": "6 months with fin 1mg and min foam — &amp;#x200B; Decided to start with minoxidilfoam and oral 1mg fin after reviewing this subreddit around end of dec 2025 and been more than 6 months now. I'm very…",
          "observedAt": "2026-07-12T21:34:01+00:00"
        }
      ],
      "freshnessDate": "2026-07-13T10:21:34.490203+00:00",
      "notes": "diversity=0.14; community=7 search=0 product=0 ad-library=0 launch=0"
    },
    {
      "nicheSlug": "lip-intimate-skincare-sensitive",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-13T10:21:29.443747+00:00",
      "notes": "diversity=0.00; community=0 search=0 product=0 ad-library=0 launch=0"
    },
    {
      "nicheSlug": "hard-water-hair-care",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-13T10:21:39.548555+00:00",
      "notes": "diversity=0.00; community=0 search=0 product=0 ad-library=0 launch=0"
    },
    {
      "nicheSlug": "beard-dandruff-beard-scalp",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-13T10:21:59.722352+00:00",
      "notes": "diversity=0.00; community=0 search=0 product=0 ad-library=0 launch=0"
    },
    {
      "nicheSlug": "post-gym-mens-skin-wipes",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-13T10:21:09.205036+00:00",
      "notes": "diversity=0.00; community=0 search=0 product=0 ad-library=0 launch=0"
    },
    {
      "nicheSlug": "delivery-rider-phone-accessories",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-13T10:21:14.246739+00:00",
      "notes": "diversity=0.00; community=0 search=0 product=0 ad-library=0 launch=0"
    },
    {
      "nicheSlug": "heat-resistant-phone-mounts",
      "demandScore": 0.30000000000000004,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [
        {
          "sourceClass": "community",
          "url": "https://reddit.com/r/motorcycles/comments/1uuzhj6/a_500_mile_review_of_the_ibex_450_from_an/",
          "source": "reddit:motorcycles",
          "snippet": "A 500 mile review of the Ibex 450, from an experienced rider — I've been riding for over 20 years, everything from sport bikes to nakeds to dual sports and enduro bikes. Wanted something a little clo…",
          "observedAt": "2026-07-13T02:56:37+00:00"
        }
      ],
      "freshnessDate": "2026-07-13T10:21:24.325991+00:00",
      "notes": "diversity=0.14; community=1 search=0 product=0 ad-library=0 launch=0"
    },
    {
      "nicheSlug": "office-chai-healthy-snacks",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-13T10:19:54.962871+00:00",
      "notes": "diversity=0.00; community=0 search=0 product=0 ad-library=0 launch=0"
    },
    {
      "nicheSlug": "diabetic-friendly-travel-snacks",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-13T10:20:30.378904+00:00",
      "notes": "diversity=0.00; community=0 search=0 product=0 ad-library=0 launch=0"
    },
    {
      "nicheSlug": "high-protein-regional-snacks",
      "demandScore": null,
      "competitionScore": 0.5,
      "pricingScore": 0.9,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [
        {
          "sourceClass": "product",
          "url": "https://www.amazon.in/dp/B0G59MC2XP",
          "source": "amazon:in",
          "snippet": "Urban Platter Roasted Salted Edamame, 150g (46% Protein, 14% Fiber, Lightly Salted Young Green Soybeans, Highest Plant Protein Supersnack) — ₹195 — 4.3 out of 5 — 386 ratings",
          "observedAt": "2026-07-13T10:22:56.928888+00:00"
        },
        {
          "sourceClass": "product",
          "url": "https://www.amazon.in/dp/B0FZHCJ8MT",
          "source": "amazon:in",
          "snippet": "Eat Anytime - Multigrain Protein Chips, Peri Peri | 40 g protein per pack | Baked, Not Fried | No Palm Oil | High Protein, Low Calories (under 160) | 150 g — ₹185 — 4.2 out of 5 — 43 ratings",
          "observedAt": "2026-07-13T10:22:56.929432+00:00"
        },
        {
          "sourceClass": "product",
          "url": "https://www.amazon.in/dp/B0CWH6TCDJ",
          "source": "amazon:in",
          "snippet": "PINTOLA 26g High Protein Oats 400g, Dark Chocolate, No Refined Sugar, with Almonds, Raisins, Pumpkin &amp; Chia Seeds, 9.6g Fibre, Rolled Oats for Weight Loss, Breakfast Cereals | Gluten Free — ₹275 — 4.4 out of 5 — 6,255 ratings",
          "observedAt": "2026-07-13T10:22:56.930068+00:00"
        },
        {
          "sourceClass": "product",
          "url": "https://www.amazon.in/dp/B0FQ2RRXMR",
          "source": "amazon:in",
          "snippet": "WellNuts &amp; Co. Pan-Roasted Protein Salad Mix (450g) | Non-Fried Healthy Snack | High Protein &amp; Fiber Rich Diet Mix | Zero Cholesterol &amp; Vegan — ₹380 — 4.3 out of 5 — 38 ratings",
          "observedAt": "2026-07-13T10:22:56.934372+00:00"
        },
        {
          "sourceClass": "product",
          "url": "https://www.amazon.in/dp/B0FTT4ZFJS",
          "source": "amazon:in",
          "snippet": "Superyou Assorted Protein Wafer Mini Bars (Pack Of 10)| 5g Protein | Made with Atta &amp; Jowar | No Added Sugar | Yeast Fermented | Energy Bars | 100% Vegetarian |No Palm Oil | 200g — ₹269 — 4.2 out of 5 — 125 ratings",
          "observedAt": "2026-07-13T10:22:56.934967+00:00"
        }
      ],
      "freshnessDate": "2026-07-13T10:22:56.935194+00:00",
      "notes": "diversity=0.14; community=0 search=0 product=5 ad-library=0 launch=0"
    },
    {
      "nicheSlug": "affordable-home-gym-under-5000",
      "demandScore": 0.85,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [
        {
          "sourceClass": "community",
          "url": "https://reddit.com/r/homegym/comments/1uuxli6/post_2020_home_gym/",
          "source": "reddit:homegym",
          "snippet": "Post 2020 home gym — Home gym I’ve been able to build with the space at my new home. Needing about 4 more mats to even out the flooring.",
          "observedAt": "2026-07-13T01:26:00+00:00"
        },
        {
          "sourceClass": "community",
          "url": "https://reddit.com/r/homegym/comments/1uuvshb/first_home_gym/",
          "source": "reddit:homegym",
          "snippet": "First Home Gym — Super crowded and not very nice looking on the TV Room but esthetics and space aside, hyped. Road to fitness 2.0 It's a Marcy SM-4033.",
          "observedAt": "2026-07-13T00:03:30+00:00"
        },
        {
          "sourceClass": "community",
          "url": "https://reddit.com/r/homegym/comments/1uui5tg/home_gym_the_before/",
          "source": "reddit:homegym",
          "snippet": "Home gym: the before — We will be expanding and entirely renovating our home gym. It’s a total mess right now because we still use it and haven’t really optimized the space since we knew we planned t…",
          "observedAt": "2026-07-12T15:14:15+00:00"
        },
        {
          "sourceClass": "community",
          "url": "https://reddit.com/r/homegym/comments/1utl73j/pacific_fitness_zuma/",
          "source": "reddit:homegym",
          "snippet": "Pacific Fitness Zuma — This is the Pacific Fitness Zuma. It has a series of single pulleys that allow me to do lat pull downs, rows, chest flys, chest press, rear delt flys, curls, tricep extensions,…",
          "observedAt": "2026-07-11T14:12:13+00:00"
        },
        {
          "sourceClass": "community",
          "url": "https://reddit.com/r/homegym/comments/1us6nrw/it_aint_much_but_its_all_i_need/",
          "source": "reddit:homegym",
          "snippet": "It ain’t much but it’s all I need — Recently bought a house with a two car garage, and have been so excited to get a little home gym set-up. Still a few more things to add, but really happy with how…",
          "observedAt": "2026-07-09T23:24:44+00:00"
        },
        {
          "sourceClass": "community",
          "url": "https://reddit.com/r/homegym/comments/1us075u/my_humble_home_gym/",
          "source": "reddit:homegym",
          "snippet": "My humble home gym — Making the most of the very small garage in a rental house! I mainly train calisthenics but would like to get a power rack setup I can replace the pull up bar with. It’s been so…",
          "observedAt": "2026-07-09T19:20:41+00:00"
        },
        {
          "sourceClass": "community",
          "url": "https://reddit.com/r/homegym/comments/1urxfpb/home_gym_renovation_no_longer_a_garage/",
          "source": "reddit:homegym",
          "snippet": "Home gym renovation. No longer a garage.",
          "observedAt": "2026-07-09T17:44:38+00:00"
        }
      ],
      "freshnessDate": "2026-07-13T10:21:19.286611+00:00",
      "notes": "diversity=0.14; community=7 search=0 product=0 ad-library=0 launch=0"
    },
    {
      "nicheSlug": "womens-gym-shorts-fit",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-13T10:18:44.053732+00:00",
      "notes": "diversity=0.00; community=0 search=0 product=0 ad-library=0 launch=0"
    },
    {
      "nicheSlug": "baby-lotions-transparent-ingredients",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-13T10:23:12.214796+00:00",
      "notes": "diversity=0.00; community=0 search=0 product=0 ad-library=0 launch=0"
    },
    {
      "nicheSlug": "ayurvedic-face-care-proof-first",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-13T10:21:54.685853+00:00",
      "notes": "diversity=0.00; community=0 search=0 product=0 ad-library=0 launch=0"
    },
    {
      "nicheSlug": "sustainable-cleaning-laundry-refills",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-13T10:22:40.281884+00:00",
      "notes": "diversity=0.00; community=0 search=0 product=0 ad-library=0 launch=0"
    },
    {
      "nicheSlug": "pet-health-supplements",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-13T10:19:19.470130+00:00",
      "notes": "diversity=0.00; community=0 search=0 product=0 ad-library=0 launch=0"
    },
    {
      "nicheSlug": "oral-care-sub-niches",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-13T10:21:49.640904+00:00",
      "notes": "diversity=0.00; community=0 search=0 product=0 ad-library=0 launch=0"
    },
    {
      "nicheSlug": "sleep-stress-support-products",
      "demandScore": 0.30000000000000004,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [
        {
          "sourceClass": "community",
          "url": "https://reddit.com/r/sleep/comments/1uv42us/anyone_else_suddenly_get_stuck_in_this_cycle/",
          "source": "reddit:sleep",
          "snippet": "Anyone else suddenly get stuck in this cycle? Daytime sleepiness → can’t sleep at night — My sleep used to be completely normal, but recently this started happening out of nowhere. Yesterday, I was s…",
          "observedAt": "2026-07-13T06:58:34+00:00"
        }
      ],
      "freshnessDate": "2026-07-13T10:18:08.612541+00:00",
      "notes": "diversity=0.14; community=1 search=0 product=0 ad-library=0 launch=0"
    },
    {
      "nicheSlug": "intimate-hygiene",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-13T10:21:44.592281+00:00",
      "notes": "diversity=0.00; community=0 search=0 product=0 ad-library=0 launch=0"
    },
    {
      "nicheSlug": "condiments-sauces-regional-identity",
      "demandScore": null,
      "competitionScore": null,
      "pricingScore": null,
      "adSaturationScore": null,
      "agentVisibilityScore": null,
      "evidence": [],
      "freshnessDate": "2026-07-13T10:22:04.776142+00:00",
      "notes": "diversity=0.00; community=0 search=0 product=0 ad-library=0 launch=0"
    }
  ]
};
