import { api } from "@/lib/api";

export const dynamic = "force-dynamic";
export const metadata = { title: "Label hit-rates — High Signal" };

type Stats = { n: number; hits: number; rate: number; lift?: number | null };

function fmtPct(x: number) {
  return `${(x * 100).toFixed(1)}%`;
}
function fmtLift(x: number | null | undefined) {
  return x == null ? "—" : `${x.toFixed(2)}×`;
}

function Bar({ rate, baselineRate }: { rate: number; baselineRate: number }) {
  // 0–1 scale, baseline marker overlaid
  const w = Math.min(rate * 100, 100);
  const bw = Math.min(baselineRate * 100, 100);
  return (
    <div className="relative h-3 w-40 overflow-hidden rounded bg-zinc-900">
      <div
        className="h-full bg-[var(--color-accent)] opacity-80"
        style={{ width: `${w}%` }}
      />
      <div
        className="absolute top-0 h-full w-px bg-zinc-300"
        style={{ left: `${bw}%` }}
        title={`baseline ${fmtPct(baselineRate)}`}
      />
    </div>
  );
}

export default async function LabelTrackRecord() {
  let data: Awaited<ReturnType<typeof api.trackRecordLabels>> | null = null;
  try {
    data = await api.trackRecordLabels();
  } catch {
    /* offline */
  }

  const rows: Array<{ key: string; label: string; stats: Stats; desc: string }> = data
    ? [
        {
          key: "breakout",
          label: "breakout",
          stats: data.labels.breakout,
          desc: "≥3 sources fire AND attention surging ≥25% — mainstream catching up",
        },
        {
          key: "divergence",
          label: "divergence",
          stats: data.labels.divergence,
          desc: "≥3 sources fire AND attention dropping — pre-news lead-time",
        },
        {
          key: "unlabeled",
          label: "unlabeled-converged",
          stats: data.unlabeled,
          desc: "≥3 sources fire but no attention trend / flat — the residual",
        },
      ]
    : [];

  return (
    <main className="mx-auto max-w-4xl px-6 py-16">
      <a
        href="/"
        className="font-mono text-[10px] uppercase tracking-[0.2em] text-zinc-500 hover:text-zinc-300"
      >
        ← high signal
      </a>
      <header className="mt-3 border-b border-zinc-800 pb-6">
        <h1 className="text-3xl font-medium tracking-tight">Label hit-rate ledger</h1>
        <p className="mt-2 max-w-2xl text-sm text-zinc-400">
          Backtest-derived calibration for the <code className="bg-zinc-900 px-1">breakout</code>{" "}
          and <code className="bg-zinc-900 px-1">divergence</code> labels rendered on{" "}
          <a href="/convergence" className="text-[var(--color-accent)] hover:underline">
            /convergence
          </a>
          . Hit = a published signal landed for that entity within 24h of the
          label being computed.{" "}
          <span className="text-zinc-600">
            Generated by{" "}
            <code className="bg-zinc-900 px-1">scripts/backtest-convergence-labels.py</code>;
            re-run to refresh.
          </span>
        </p>
        {data ? (
          <div className="mt-3 font-mono text-[10px] uppercase tracking-[0.18em] text-zinc-500">
            backtest window: {data.backtestDays}d  ·  generated{" "}
            {data.generatedAt.slice(0, 16).replace("T", " ")} UTC
          </div>
        ) : null}
      </header>

      {data ? (
        <>
          <section className="mt-8 border border-zinc-800 p-4">
            <div className="font-mono text-[10px] uppercase tracking-[0.18em] text-zinc-500">
              baseline — any converged entity (≥3 sources, 24h window)
            </div>
            <div className="mt-2 flex items-baseline gap-3 text-sm">
              <span className="font-mono text-zinc-100">{fmtPct(data.baseline.rate)}</span>
              <span className="text-zinc-500">
                {data.baseline.hits} / {data.baseline.n} entity-days had a signal in the next 24h
              </span>
            </div>
          </section>

          <table className="mt-6 w-full text-sm">
            <thead className="font-mono text-[10px] uppercase tracking-[0.18em] text-zinc-500">
              <tr className="border-b border-zinc-800">
                <th className="py-2 text-left">label</th>
                <th className="py-2 text-left">n</th>
                <th className="py-2 text-left">hits</th>
                <th className="py-2 text-left">rate</th>
                <th className="py-2 text-left">lift</th>
                <th className="py-2 text-left">vs baseline</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((r) => (
                <tr key={r.key} className="border-b border-zinc-900">
                  <td className="py-3 align-top">
                    <div className="font-mono text-zinc-100">{r.label}</div>
                    <div className="text-xs text-zinc-500">{r.desc}</div>
                  </td>
                  <td className="py-3 align-top font-mono text-zinc-300">{r.stats.n}</td>
                  <td className="py-3 align-top font-mono text-zinc-300">{r.stats.hits}</td>
                  <td className="py-3 align-top font-mono">
                    <span
                      className={
                        r.stats.rate > data.baseline.rate
                          ? "text-emerald-300"
                          : r.stats.rate < data.baseline.rate
                            ? "text-red-300"
                            : "text-zinc-300"
                      }
                    >
                      {fmtPct(r.stats.rate)}
                    </span>
                  </td>
                  <td className="py-3 align-top font-mono text-zinc-300">{fmtLift(r.stats.lift)}</td>
                  <td className="py-3 align-top">
                    <Bar rate={r.stats.rate} baselineRate={data.baseline.rate} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>

          <p className="mt-6 text-xs text-zinc-500">
            Bar: solid = label hit-rate, vertical tick = baseline. To the right of the tick
            means the label produces signal above what you'd get from any converged entity at
            random.
          </p>
        </>
      ) : (
        <div className="mt-12 border border-dashed border-zinc-800 p-10 text-center font-mono text-[11px] uppercase tracking-[0.18em] text-zinc-500">
          no backtest data yet — run scripts/backtest-convergence-labels.py
        </div>
      )}
    </main>
  );
}
