#!/usr/bin/env node
/**
 * Bundle the latest `data/d2c-opportunities/<YYYY-MM-DD>.json` artifact into
 * `packages/shared/src/content/d2c-opportunities-artifact.ts` so the worker
 * and web app can render the latest cited evidence without a runtime
 * filesystem read (both deploy to Cloudflare Workers).
 *
 * Run after the weekly collector:
 *   uv run python -m high_signal_ingest.d2c_opportunities
 *   pnpm d2c:bundle
 *
 * When no artifact exists, the bundled value stays `null` and the renderer
 * falls back to seed-only briefs.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const ARTIFACT_DIR = resolve(ROOT, "data/d2c-opportunities");
const OUT_FILE = resolve(
  ROOT,
  "packages/shared/src/content/d2c-opportunities-artifact.ts",
);

async function main() {
  let names: string[];
  try {
    names = await readdir(ARTIFACT_DIR);
  } catch {
    console.log(`[d2c:bundle] no artifact dir at ${ARTIFACT_DIR}; writing null`);
    await writeArtifact(null);
    return;
  }
  const dated = names
    .filter((n) => /^\d{4}-\d{2}-\d{2}\.json$/.test(n))
    .sort()
    .reverse();
  if (dated.length === 0) {
    console.log(`[d2c:bundle] no dated artifact in ${ARTIFACT_DIR}; writing null`);
    await writeArtifact(null);
    return;
  }
  const latest = dated[0];
  const raw = await readFile(resolve(ARTIFACT_DIR, latest), "utf-8");
  // Validate it parses as JSON before writing it into the bundle.
  JSON.parse(raw);
  console.log(`[d2c:bundle] bundling ${latest}`);
  await writeArtifact(raw.trim());
}

async function writeArtifact(jsonLiteral: string | null) {
  const value = jsonLiteral ?? "null";
  const content = `/**
 * Build-time bundled India D2C opportunity artifact.
 *
 * This file is regenerated by \`scripts/d2c-opportunities-bundle.ts\` after the
 * weekly collector (\`python/ingest/.../d2c_opportunities.py\`) writes a new
 * \`data/d2c-opportunities/<YYYY-MM-DD>.json\`. The worker and web app import
 * this module so they can render the latest cited evidence without a runtime
 * filesystem read (both deploy to Cloudflare Workers).
 *
 * When no artifact has been generated yet, this is \`null\` and the renderer
 * falls back to seed-only briefs (conservative \`watch\` verdicts).
 *
 * DO NOT edit by hand — run \`pnpm d2c:bundle\` after a collector run.
 */

import type { D2COpportunityArtifact } from "./d2c-opportunities";

export const BUNDLED_D2C_ARTIFACT: D2COpportunityArtifact | null = ${value};
`;
  await writeFile(OUT_FILE, content, "utf-8");
  console.log(`[d2c:bundle] wrote ${OUT_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
