export const ATTENTION_SOURCE_CATALOG = [
  {
    id: 'digg',
    provider: 'Digg technology clusters',
    domains: 'technology / AI',
    access: 'keyless',
    official: false,
    windowDays: 2,
    role: 'attention',
    keeps: 'rank, velocity, contributing voices, source links, local snapshots',
    temporal: 'recent',
    cadence: 'half_hourly',
    expectedRunCadenceHours: 0.5,
    accessBasis: 'Five documented public Digg feeds; attention and discovery only.',
    contentDepth: 'documented feed metadata and snapshots',
    retention: 'D1 cluster history; never counts as evidence or confidence.',
    termsRisk: 'reference-only',
  },
  {
    id: 'mts',
    provider: 'MTS Situations',
    domains: 'technology / AI',
    access: 'keyless',
    official: false,
    windowDays: 2,
    role: 'attention',
    keeps: 'rank, velocity, entities, topics, source URLs, local snapshots',
    temporal: 'recent',
    cadence: 'half_hourly',
    expectedRunCadenceHours: 0.5,
    accessBasis: 'Documented public MTS Situations API; attention and discovery only.',
    contentDepth: 'compact reference metadata; no descriptions, post text, avatars or raw mirror',
    retention: 'D1 rank/reference history; never counts as evidence or confidence.',
    termsRisk: 'reference-only',
  },
] as const;
